#!/usr/bin/env python3

import sys
import json
from subprocess import run

json.load(sys.stdin)

for unit in ["rag-sync.timer", "rag-maintenance.timer", "rag.service"]:
    run(["systemctl", "--user", "disable", "--now", unit], check=False)
